name: Daily Maintenance

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make routine update
        run: |
          echo "// updated on $(date)" >> utils.js
          git config user.name "BABEEEZ"
          git config user.email "Bbab3369@gmail.com"
          git add utils.js
          git commit -m "chore: routine update"
          git push
